image: node:14.15.5

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
  - prepare
  - test
  - sonarcloud-check
  - deploy

prepare:
  stage: prepare
  cache:
    key: node-modules-cache
    paths:
      - node_modules
  script:
    - npm install

test:
  stage: test
  cache:
    key: node-modules-cache
    paths:
      - node_modules
  script:
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 10 mins
    paths:
      - coverage/lcov.info
      - coverage/clover.xml
  dependencies:
    - prepare

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarcloud-check
  dependencies:
    - test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - main

deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  dependencies:
    - test
    - sonarcloud-check
  only:
    - main
  script:
    - echo $GCP_SERVICE_KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $GCP_PROJECT_ID app deploy app.yaml